import sqlite3 
DB_name = 'routes.db'
def init_db():
    conn = sqlite3.connect(DB_name)
    cursor = conn.cursor()
    cursor.execute('''
        CREATE TABLE IF NOT EXISTS routes (
            origin TEXT,
            destination TEXT,
            route TEXT,
            altitude TEXT,
            notes TEXT
        )
    ''')
    routes = [("CLE", "ORD", "GTLKE4 DAIFE WATSN WATSN4", "", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "MDW", "GTLKE4 BAGEL PANGG5", "", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "MKE", "GTLKE4 ALPHE PEGEE GETCH LYSTR SUDDS", "", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "BOS", "PFLYD1 JASEE JHW Q82 PONCT JFUND2", "", ""),
    ("BKL", "BOS", "MYCAR4 MYCAR JHW Q82 PONCT JFUND2", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "BDL", "PFLYD1 JASEE JHW Q82 MEMMS WILET STELA1", "", ""),
    ("BKL", "BDL", "MYCAR4 MYCAR JHW Q82 MEMMS WILET STELA1", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "BWI", "KKIDS1 NUSMM ANTHM5", "", ""),
    ("BKL", "BWI", "AHMET4 NUSMM ANTHM5", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "DCA", "KKIDS1 NUSMM BUCKO FRDMM6", "", ""),
    ("BKL", "DCA", "AHMET4 NUSMM BUCKO FRDMM6", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "IAD", "KKIDS1 NUSMM MGW GIBBZ5", "", ""),
    ("BKL", "IAD", "AHMET4 NUSMM MGW GIBBZ5", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),    
    ("CLE", "ORF", "KKIDS1 NUSMM MGW MOL TERKS2", "", ""),
    ("BKL", "ORF", "AHMET4 NUSMM MGW MOL TERKS2", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "CMH", "WWSHR CBUSS2", "", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "CVG", "CAVVS4 CAVVS UKATS TIGGR4", "FL220B", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "IND", "ZAAPA5 SINKR SNKPT2", "FL220B", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "SDF", "CAVVS4 CAVVS UKATS DLAMP8", "FL280B", "From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "MSP", "GTLKE4 ALPHE VIO KAMMA KKILR3", "", "Through ZAU, From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "EWR", "PFLYD1 DORET J584 SLT FQM3", "", ""),
    ("BKL", "EWR", "MYCAR4 MYCAR ZORBO J584 SLT FQM3", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "JFK", "PFLYD1 JASEE JHW J70 LVZ LENDY8", "", ""),
    ("BKL", "JFK", "MYCAR4 MYCAR JHW J70 LVZ LENDY8", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "LGA", "PFLYD1 MAAJR ETG MIP4", "", ""),
    ("BKL", "LGA", "MYCAR4 MYCAR ETG MIP4", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "PHL", "KKIDS1 EWC JST BOJID4", "", ""),
    ("BKL", "PHL", "AHMET4 EWC JST BOJID4", "", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "YYZ", "PFLYD1 PATRC FINGL NUBER6", "FL190B", ""),
    ("BKL", "YYZ", "MYCAR4 MYCAR FINGL NUBER6", "FL190B", "From Cleveland Sats only (BKL,CGF,LNN,LPR)"),
    ("CLE", "DTW", "BONZZ BONZZ2", "", "DTW south, From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("CLE", "DTW", "BONZZ KLYNK3", "", "DTW north, From Cleveland Metro (CLE,CGF,BKL,LNN,LPR)"),
    ("BUF", "ORD", "DAVVK FARGN CHAAP Q436 EMMMA WYNDE2", "", ""),
    ("BUF", "MDW", "JHW DJB J60 ASHEN BAGEL PANGG5", "", ""),
    ("BUF", "BOS", "GEE PONCT JFUND2", "", ""),
    ("BUF", "MKE", "DERLO Q935 HOCKE GETCH LYSTR SUDDS", "", ""),
    ("BUF", "BDL", "GEE BEEPS WILET STELA1", "", ""),
    ("BUF", "BWI", "VAIRS DDUBS IZZEE TRISH4", "", "Through ZNY"),
    ("BUF", "DCA", "VAIRS PSB SKILS5", "", "Through ZNY"),
    ("BUF", "IAD", "VAIRS PSB WAYNZ1", "", "Through ZNY"),
    ("BUF", "CMH", "JHW WWSHR CBUSS2", "", ""),
    ("BUF", "CVG", "DKK ACO UKATS TIGRR4", "", ""),
    ("BUF", "IND", "JHW DJB RINTE SNKPT2", "", ""),
    ("BUF", "SDF", "JHW UKATS DLAMP8", "", ""),
    ("BUF", "MSP", "DERLO HOCKE IDIOM MUSCL3", "", ""),
    ("BUF", "EWR", "GEE BEEPS Q140 KODEY HNK FLOSI4", "", ""),
    ("BUF", "JFK", "GEE BEEPS IGN IGN1", "", ""),
    ("BUF", "LGA", "GEE RKA HAARP4", "", ""),
    ("BUF", "PHL", "BFD PSB BOJID4", "", ""),
    ("BUF", "YYZ", "ISTON LINNG3", "16000B", ""),
    ("BUF", "DTW", "DONEO TPGUN2", "", "DTW south"),
    ("BUF", "DTW", "DONEO CUUGR", "", "DTW north"),
    ("DTW", "ORD", "KAYLN3 SMUUV WYNDE2", "FL280B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "MDW", "CCOBB3 ZEGBI LEROY BAGEL PANGG5", "FL220B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "BOS", "HHOWE4 LNCON JHW Q82 PONCT JFUND2", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "MKE", "MIGGY3 GETCH LYSTR SUDDS", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "BDL", "HHOWE4 LNCON JHW Q82 MEMMS WILET STELA1", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "BWI", "LIDDS3 GRIVY NUSMM ANTHM5", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "DCA", "LIDDS3 GRIVY BUCKO FRDMM6", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "IAD", "LIDDS3 GRIVY AIR MGW GIBBZ5", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "CMH", "CLVIN3 CLVIN ESSIE DUBLN1", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "CVG", "SNDRS3 TORRR DEBAR ARBAS RID MEEKR", "FL200B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "IND", "SNDRS3 TORRR SNKPT CLANG7", "FL220B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "SDF", "CLVIN3 CLVIN RINTE DLAMP8", "FL280B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "MSP", "MIGGY3 SLLAP Q440 IDIOM MUSCL3", "", "Preferred, From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "MSP", "KAYLN3 SMUUV KAMMA KKILR3", "", "Through ZAU, From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "EWR", "PAVYL3 ESSBE SLT FQM3", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "JFK", "PAVYL3 MRDOC HOXIE J70 LVZ LENDY8", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "LGA", "PAVYL3 ESSBE CXR ETG MIP4", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "PHL", "PAVYL3 ESSBE CXR EWC JST BOJID4", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "YYZ", "ZETTR4 TANKO APDAX NUBER6", "FL210B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "CLE", "KZLOV2 WINNZ BRWNZ4", "", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)"),
    ("DTW", "BUF", "HHOWE4 BROKK DKK", "FL270B", "From Detroit Metro (DTW,DET,PTK,YIP,ARB)")]

    cursor.executemany('INSERT INTO routes VALUES (?, ?, ?, ?, ?)',routes)
    conn.commit()
    conn.close()
init_db()